### ISSUE TITLE
'Edit styles' cmd on Linux

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_color_text#4]
crash
```
Python 3.5.3
Init: cuda_config_toolbar
Init: cuda_tabs_list
Loading toolbar config
Init: cuda_project_man
Startup: total: 37628ms, including plugins: 44ms
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cudatext_color_text/__init__.py", line 21, in <module>
    shutil.copyfile(ini0, ini)
  File "/usr/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/tools/settings/styles.ini'
```

**Comment by Alexey-T** [comment]
ini = os.path.join(app_path(APP_DIR_SETTINGS), 'styles.ini')
